services:
  cloud:
    build:
      context: ./
    container_name: cloud
    image: nextcloud:31.0.2
    restart: always
    environment:
      - MYSQL_HOST=cloud-db
      - MYSQL_PASSWORD=${CLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=${CLOUD_DATABASE}
      - MYSQL_USER=${CLOUD_DB_USER}
      - APACHE_DISABLE_REWRITE_IP=1
      - OVERWRITEWEBROOT=/nextcloud
      - CLOUD_ADMIN_USER=${CLOUD_ADMIN_USER}
      - CLOUD_ADMIN_PASSWORD=${CLOUD_ADMIN_PASSWORD}

    volumes:
      - cloud:/var/www/html
    links:
      - cloud-db
      - redis

  cloud-db:
    container_name: cloud-db
    image: mariadb:11.4
    restart: always
    environment:
      - MARIADB_DATABASE=${CLOUD_DATABASE}
      - MARIADB_USER=${CLOUD_DB_USER}
      - MARIADB_PASSWORD=${CLOUD_DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${CLOUD_DB_ROOT_PASSWORD}
    tty: true
    volumes:
      - cloud-db:/var/lib/mysql
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on:
      - cloud
  
  nginx-web:
    image: nginx
    container_name: web
    restart: always
    volumes:
      - ./webContents:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

volumes:
  cloud:
    driver_opts:
      type: none
      device: /Users/sinohiro/git/syoriken/my-service/cloud-app
      o: bind
  cloud-db: 
    driver_opts:
      type: none
      device: /Users/sinohiro/git/syoriken/my-service/cloud-db
      o: bind